### ISSUE TITLE
Broken in Brackets 1.14 ?

### ISSUE THREAD

**Issue by TD540** [pockata/brackets-StripTrailingSpaces#10]
Seems like this plugin is not working on my Mac with Mojave 10.14.6 and Brackets 1.14

I've got the "Strip trailing spaces" option enabled in the Edit menu. I've tried restarting Brackets and saving again, still trailing spaces remain.

**Comment by pockata** [comment]
Hey, thanks for taking the time to file this issue!

I took a quick look, but everything is working as expected for me. I
tested with a fresh install of Brackets 1.14.1 and the
StripTrailingSpaces extension.

Perhaps there might be a collision with one of your other extensions?
You might try disabling them and testing if that changes something.

Also you can check the error console for any relevant errors. Use the
menu and navigate to "Debug" -> "Show Developer Tools" and then click
the "Console" tab. Please attach a screenshot of the output.

There seems to be a few deprecation warnings in relation to
StripTrailingSpaces (which I'll take care of soon), but these don't seem
to affect the functionality of the plugin.
