### ISSUE TITLE
Error while loading in Brackets 1.9

### ISSUE THREAD

**Issue by artquest** [pockata/brackets-StripTrailingSpaces#8]
Error while loading (not loaded) in Brackets new release (1.9).

**Comment by pockata** [comment]
Whoa, I hadn't realized someone was still using this plugin. Thanks for the heads up!

I'll update it in the next few days when I have some free time.
@artquest Please ping me in a week if I don't update this issue (in case I forget).

**Comment by nrigaudiere** [comment]
Your plugin rocks buddy! Can't wait for a fix for the new Brackets release ;)

Cheers!

**Comment by artquest** [comment]
@nrigaudiere 
There's an alternative solution, [https://github.com/MiguelCastillo/Brackets-wsSanitizer](Space Sanitizer) extension. It has the ability to wipe redundant spaces on file save plus much more. And it works on 1.9

**Comment by nrigaudiere** [comment]
@artquest Life saving! Thanks!

**Comment by pockata** [comment]
A little late, but I have updated the plugin to work with with Brackets 1.9
