### ISSUE TITLE
I've installed this plugin in my brackets

### ISSUE THREAD

**Issue by ghost** [pockata/brackets-StripTrailingSpaces#9]
I've installed this plugin in my brackets. but iI dont know how it works, so is that any clue for it?
thanks

**Comment by pockata** [comment]
Hey there!

There's not much to this plugin. After installing it, just make sure that the auto-trimming on save functionality is on by checking the `Edit > Strip trailing space` option from the menu inside Brackets.

After that's done trailing whitespace should be automatically removed when you save a file.

**Comment by boldt** [comment]
Unfortunately, it does not indicate whether its activated or not.

**Comment by pockata** [comment]
@boldt I guessed the checkmark in front of the option is clear enough. Are you seeing something different than the screenshot below?

![Brackets screenshot](https://puu.sh/zRepn/c314b1c5e5.png)

If that's not what you're seeing, please give me some additional info about your setup (OS, Brackets version, StripTrailingSpaces version, etc.) so I can debug it.

**Comment by boldt** [comment]
On my Ubuntu, I do not have any indication:

![bildschirmfoto vom 2018-04-08 18 48 20](https://user-images.githubusercontent.com/750793/38470012-7b14372a-3b5d-11e8-8727-9eb5d36dee1a.png)

It seems to be a global issue for all options.

**Comment by pockata** [comment]
Closing as issue is not relevant to StripTrailingSpaces
